// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StockTicks.proto

package org.example.model.protobuf;

public final class StockTicksProto {
  private StockTicksProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StockTicksOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.example.model.protobuf.StockTicks)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 volume = 1;</code>
     * @return The volume.
     */
    long getVolume();

    /**
     * <code>string symbol = 2;</code>
     * @return The symbol.
     */
    java.lang.String getSymbol();
    /**
     * <code>string symbol = 2;</code>
     * @return The bytes for symbol.
     */
    com.google.protobuf.ByteString
        getSymbolBytes();

    /**
     * <code>string ts = 3;</code>
     * @return The ts.
     */
    java.lang.String getTs();
    /**
     * <code>string ts = 3;</code>
     * @return The bytes for ts.
     */
    com.google.protobuf.ByteString
        getTsBytes();

    /**
     * <code>string month = 4;</code>
     * @return The month.
     */
    java.lang.String getMonth();
    /**
     * <code>string month = 4;</code>
     * @return The bytes for month.
     */
    com.google.protobuf.ByteString
        getMonthBytes();

    /**
     * <code>double high = 5;</code>
     * @return The high.
     */
    double getHigh();

    /**
     * <code>double low = 6;</code>
     * @return The low.
     */
    double getLow();

    /**
     * <code>string key = 7;</code>
     * @return The key.
     */
    java.lang.String getKey();
    /**
     * <code>string key = 7;</code>
     * @return The bytes for key.
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <code>int32 year = 8;</code>
     * @return The year.
     */
    int getYear();

    /**
     * <code>string date = 9;</code>
     * @return The date.
     */
    java.lang.String getDate();
    /**
     * <code>string date = 9;</code>
     * @return The bytes for date.
     */
    com.google.protobuf.ByteString
        getDateBytes();

    /**
     * <code>double close = 10;</code>
     * @return The close.
     */
    double getClose();

    /**
     * <code>double open = 11;</code>
     * @return The open.
     */
    double getOpen();

    /**
     * <code>string day = 12;</code>
     * @return The day.
     */
    java.lang.String getDay();
    /**
     * <code>string day = 12;</code>
     * @return The bytes for day.
     */
    com.google.protobuf.ByteString
        getDayBytes();
  }
  /**
   * Protobuf type {@code org.example.model.protobuf.StockTicks}
   */
  public  static final class StockTicks extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.example.model.protobuf.StockTicks)
      StockTicksOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use StockTicks.newBuilder() to construct.
    private StockTicks(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StockTicks() {
      symbol_ = "";
      ts_ = "";
      month_ = "";
      key_ = "";
      date_ = "";
      day_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new StockTicks();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private StockTicks(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              volume_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              symbol_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              ts_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              month_ = s;
              break;
            }
            case 41: {

              high_ = input.readDouble();
              break;
            }
            case 49: {

              low_ = input.readDouble();
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              key_ = s;
              break;
            }
            case 64: {

              year_ = input.readInt32();
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              date_ = s;
              break;
            }
            case 81: {

              close_ = input.readDouble();
              break;
            }
            case 89: {

              open_ = input.readDouble();
              break;
            }
            case 98: {
              java.lang.String s = input.readStringRequireUtf8();

              day_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.model.protobuf.StockTicksProto.internal_static_org_example_model_protobuf_StockTicks_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.model.protobuf.StockTicksProto.internal_static_org_example_model_protobuf_StockTicks_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.model.protobuf.StockTicksProto.StockTicks.class, org.example.model.protobuf.StockTicksProto.StockTicks.Builder.class);
    }

    public static final int VOLUME_FIELD_NUMBER = 1;
    private long volume_;
    /**
     * <code>int64 volume = 1;</code>
     * @return The volume.
     */
    public long getVolume() {
      return volume_;
    }

    public static final int SYMBOL_FIELD_NUMBER = 2;
    private volatile java.lang.Object symbol_;
    /**
     * <code>string symbol = 2;</code>
     * @return The symbol.
     */
    public java.lang.String getSymbol() {
      java.lang.Object ref = symbol_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        symbol_ = s;
        return s;
      }
    }
    /**
     * <code>string symbol = 2;</code>
     * @return The bytes for symbol.
     */
    public com.google.protobuf.ByteString
        getSymbolBytes() {
      java.lang.Object ref = symbol_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        symbol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TS_FIELD_NUMBER = 3;
    private volatile java.lang.Object ts_;
    /**
     * <code>string ts = 3;</code>
     * @return The ts.
     */
    public java.lang.String getTs() {
      java.lang.Object ref = ts_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ts_ = s;
        return s;
      }
    }
    /**
     * <code>string ts = 3;</code>
     * @return The bytes for ts.
     */
    public com.google.protobuf.ByteString
        getTsBytes() {
      java.lang.Object ref = ts_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ts_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MONTH_FIELD_NUMBER = 4;
    private volatile java.lang.Object month_;
    /**
     * <code>string month = 4;</code>
     * @return The month.
     */
    public java.lang.String getMonth() {
      java.lang.Object ref = month_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        month_ = s;
        return s;
      }
    }
    /**
     * <code>string month = 4;</code>
     * @return The bytes for month.
     */
    public com.google.protobuf.ByteString
        getMonthBytes() {
      java.lang.Object ref = month_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        month_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HIGH_FIELD_NUMBER = 5;
    private double high_;
    /**
     * <code>double high = 5;</code>
     * @return The high.
     */
    public double getHigh() {
      return high_;
    }

    public static final int LOW_FIELD_NUMBER = 6;
    private double low_;
    /**
     * <code>double low = 6;</code>
     * @return The low.
     */
    public double getLow() {
      return low_;
    }

    public static final int KEY_FIELD_NUMBER = 7;
    private volatile java.lang.Object key_;
    /**
     * <code>string key = 7;</code>
     * @return The key.
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        key_ = s;
        return s;
      }
    }
    /**
     * <code>string key = 7;</code>
     * @return The bytes for key.
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int YEAR_FIELD_NUMBER = 8;
    private int year_;
    /**
     * <code>int32 year = 8;</code>
     * @return The year.
     */
    public int getYear() {
      return year_;
    }

    public static final int DATE_FIELD_NUMBER = 9;
    private volatile java.lang.Object date_;
    /**
     * <code>string date = 9;</code>
     * @return The date.
     */
    public java.lang.String getDate() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        date_ = s;
        return s;
      }
    }
    /**
     * <code>string date = 9;</code>
     * @return The bytes for date.
     */
    public com.google.protobuf.ByteString
        getDateBytes() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        date_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLOSE_FIELD_NUMBER = 10;
    private double close_;
    /**
     * <code>double close = 10;</code>
     * @return The close.
     */
    public double getClose() {
      return close_;
    }

    public static final int OPEN_FIELD_NUMBER = 11;
    private double open_;
    /**
     * <code>double open = 11;</code>
     * @return The open.
     */
    public double getOpen() {
      return open_;
    }

    public static final int DAY_FIELD_NUMBER = 12;
    private volatile java.lang.Object day_;
    /**
     * <code>string day = 12;</code>
     * @return The day.
     */
    public java.lang.String getDay() {
      java.lang.Object ref = day_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        day_ = s;
        return s;
      }
    }
    /**
     * <code>string day = 12;</code>
     * @return The bytes for day.
     */
    public com.google.protobuf.ByteString
        getDayBytes() {
      java.lang.Object ref = day_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        day_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (volume_ != 0L) {
        output.writeInt64(1, volume_);
      }
      if (!getSymbolBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, symbol_);
      }
      if (!getTsBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, ts_);
      }
      if (!getMonthBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, month_);
      }
      if (high_ != 0D) {
        output.writeDouble(5, high_);
      }
      if (low_ != 0D) {
        output.writeDouble(6, low_);
      }
      if (!getKeyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, key_);
      }
      if (year_ != 0) {
        output.writeInt32(8, year_);
      }
      if (!getDateBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, date_);
      }
      if (close_ != 0D) {
        output.writeDouble(10, close_);
      }
      if (open_ != 0D) {
        output.writeDouble(11, open_);
      }
      if (!getDayBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 12, day_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (volume_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, volume_);
      }
      if (!getSymbolBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, symbol_);
      }
      if (!getTsBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, ts_);
      }
      if (!getMonthBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, month_);
      }
      if (high_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, high_);
      }
      if (low_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, low_);
      }
      if (!getKeyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, key_);
      }
      if (year_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, year_);
      }
      if (!getDateBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, date_);
      }
      if (close_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(10, close_);
      }
      if (open_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(11, open_);
      }
      if (!getDayBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, day_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.example.model.protobuf.StockTicksProto.StockTicks)) {
        return super.equals(obj);
      }
      org.example.model.protobuf.StockTicksProto.StockTicks other = (org.example.model.protobuf.StockTicksProto.StockTicks) obj;

      if (getVolume()
          != other.getVolume()) return false;
      if (!getSymbol()
          .equals(other.getSymbol())) return false;
      if (!getTs()
          .equals(other.getTs())) return false;
      if (!getMonth()
          .equals(other.getMonth())) return false;
      if (java.lang.Double.doubleToLongBits(getHigh())
          != java.lang.Double.doubleToLongBits(
              other.getHigh())) return false;
      if (java.lang.Double.doubleToLongBits(getLow())
          != java.lang.Double.doubleToLongBits(
              other.getLow())) return false;
      if (!getKey()
          .equals(other.getKey())) return false;
      if (getYear()
          != other.getYear()) return false;
      if (!getDate()
          .equals(other.getDate())) return false;
      if (java.lang.Double.doubleToLongBits(getClose())
          != java.lang.Double.doubleToLongBits(
              other.getClose())) return false;
      if (java.lang.Double.doubleToLongBits(getOpen())
          != java.lang.Double.doubleToLongBits(
              other.getOpen())) return false;
      if (!getDay()
          .equals(other.getDay())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VOLUME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getVolume());
      hash = (37 * hash) + SYMBOL_FIELD_NUMBER;
      hash = (53 * hash) + getSymbol().hashCode();
      hash = (37 * hash) + TS_FIELD_NUMBER;
      hash = (53 * hash) + getTs().hashCode();
      hash = (37 * hash) + MONTH_FIELD_NUMBER;
      hash = (53 * hash) + getMonth().hashCode();
      hash = (37 * hash) + HIGH_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getHigh()));
      hash = (37 * hash) + LOW_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getLow()));
      hash = (37 * hash) + KEY_FIELD_NUMBER;
      hash = (53 * hash) + getKey().hashCode();
      hash = (37 * hash) + YEAR_FIELD_NUMBER;
      hash = (53 * hash) + getYear();
      hash = (37 * hash) + DATE_FIELD_NUMBER;
      hash = (53 * hash) + getDate().hashCode();
      hash = (37 * hash) + CLOSE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getClose()));
      hash = (37 * hash) + OPEN_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getOpen()));
      hash = (37 * hash) + DAY_FIELD_NUMBER;
      hash = (53 * hash) + getDay().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.example.model.protobuf.StockTicksProto.StockTicks parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.model.protobuf.StockTicksProto.StockTicks parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.model.protobuf.StockTicksProto.StockTicks parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.model.protobuf.StockTicksProto.StockTicks parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.model.protobuf.StockTicksProto.StockTicks parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.model.protobuf.StockTicksProto.StockTicks parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.model.protobuf.StockTicksProto.StockTicks parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.example.model.protobuf.StockTicksProto.StockTicks parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.model.protobuf.StockTicksProto.StockTicks parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.example.model.protobuf.StockTicksProto.StockTicks parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.model.protobuf.StockTicksProto.StockTicks parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.example.model.protobuf.StockTicksProto.StockTicks parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.example.model.protobuf.StockTicksProto.StockTicks prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.example.model.protobuf.StockTicks}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.example.model.protobuf.StockTicks)
        org.example.model.protobuf.StockTicksProto.StockTicksOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.example.model.protobuf.StockTicksProto.internal_static_org_example_model_protobuf_StockTicks_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.example.model.protobuf.StockTicksProto.internal_static_org_example_model_protobuf_StockTicks_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.example.model.protobuf.StockTicksProto.StockTicks.class, org.example.model.protobuf.StockTicksProto.StockTicks.Builder.class);
      }

      // Construct using org.example.model.protobuf.StockTicksProto.StockTicks.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        volume_ = 0L;

        symbol_ = "";

        ts_ = "";

        month_ = "";

        high_ = 0D;

        low_ = 0D;

        key_ = "";

        year_ = 0;

        date_ = "";

        close_ = 0D;

        open_ = 0D;

        day_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.example.model.protobuf.StockTicksProto.internal_static_org_example_model_protobuf_StockTicks_descriptor;
      }

      @java.lang.Override
      public org.example.model.protobuf.StockTicksProto.StockTicks getDefaultInstanceForType() {
        return org.example.model.protobuf.StockTicksProto.StockTicks.getDefaultInstance();
      }

      @java.lang.Override
      public org.example.model.protobuf.StockTicksProto.StockTicks build() {
        org.example.model.protobuf.StockTicksProto.StockTicks result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.example.model.protobuf.StockTicksProto.StockTicks buildPartial() {
        org.example.model.protobuf.StockTicksProto.StockTicks result = new org.example.model.protobuf.StockTicksProto.StockTicks(this);
        result.volume_ = volume_;
        result.symbol_ = symbol_;
        result.ts_ = ts_;
        result.month_ = month_;
        result.high_ = high_;
        result.low_ = low_;
        result.key_ = key_;
        result.year_ = year_;
        result.date_ = date_;
        result.close_ = close_;
        result.open_ = open_;
        result.day_ = day_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.example.model.protobuf.StockTicksProto.StockTicks) {
          return mergeFrom((org.example.model.protobuf.StockTicksProto.StockTicks)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.example.model.protobuf.StockTicksProto.StockTicks other) {
        if (other == org.example.model.protobuf.StockTicksProto.StockTicks.getDefaultInstance()) return this;
        if (other.getVolume() != 0L) {
          setVolume(other.getVolume());
        }
        if (!other.getSymbol().isEmpty()) {
          symbol_ = other.symbol_;
          onChanged();
        }
        if (!other.getTs().isEmpty()) {
          ts_ = other.ts_;
          onChanged();
        }
        if (!other.getMonth().isEmpty()) {
          month_ = other.month_;
          onChanged();
        }
        if (other.getHigh() != 0D) {
          setHigh(other.getHigh());
        }
        if (other.getLow() != 0D) {
          setLow(other.getLow());
        }
        if (!other.getKey().isEmpty()) {
          key_ = other.key_;
          onChanged();
        }
        if (other.getYear() != 0) {
          setYear(other.getYear());
        }
        if (!other.getDate().isEmpty()) {
          date_ = other.date_;
          onChanged();
        }
        if (other.getClose() != 0D) {
          setClose(other.getClose());
        }
        if (other.getOpen() != 0D) {
          setOpen(other.getOpen());
        }
        if (!other.getDay().isEmpty()) {
          day_ = other.day_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.example.model.protobuf.StockTicksProto.StockTicks parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.example.model.protobuf.StockTicksProto.StockTicks) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long volume_ ;
      /**
       * <code>int64 volume = 1;</code>
       * @return The volume.
       */
      public long getVolume() {
        return volume_;
      }
      /**
       * <code>int64 volume = 1;</code>
       * @param value The volume to set.
       * @return This builder for chaining.
       */
      public Builder setVolume(long value) {
        
        volume_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 volume = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearVolume() {
        
        volume_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object symbol_ = "";
      /**
       * <code>string symbol = 2;</code>
       * @return The symbol.
       */
      public java.lang.String getSymbol() {
        java.lang.Object ref = symbol_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          symbol_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string symbol = 2;</code>
       * @return The bytes for symbol.
       */
      public com.google.protobuf.ByteString
          getSymbolBytes() {
        java.lang.Object ref = symbol_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          symbol_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string symbol = 2;</code>
       * @param value The symbol to set.
       * @return This builder for chaining.
       */
      public Builder setSymbol(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        symbol_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string symbol = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSymbol() {
        
        symbol_ = getDefaultInstance().getSymbol();
        onChanged();
        return this;
      }
      /**
       * <code>string symbol = 2;</code>
       * @param value The bytes for symbol to set.
       * @return This builder for chaining.
       */
      public Builder setSymbolBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        symbol_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object ts_ = "";
      /**
       * <code>string ts = 3;</code>
       * @return The ts.
       */
      public java.lang.String getTs() {
        java.lang.Object ref = ts_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ts_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ts = 3;</code>
       * @return The bytes for ts.
       */
      public com.google.protobuf.ByteString
          getTsBytes() {
        java.lang.Object ref = ts_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ts_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ts = 3;</code>
       * @param value The ts to set.
       * @return This builder for chaining.
       */
      public Builder setTs(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ts_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ts = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTs() {
        
        ts_ = getDefaultInstance().getTs();
        onChanged();
        return this;
      }
      /**
       * <code>string ts = 3;</code>
       * @param value The bytes for ts to set.
       * @return This builder for chaining.
       */
      public Builder setTsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ts_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object month_ = "";
      /**
       * <code>string month = 4;</code>
       * @return The month.
       */
      public java.lang.String getMonth() {
        java.lang.Object ref = month_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          month_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string month = 4;</code>
       * @return The bytes for month.
       */
      public com.google.protobuf.ByteString
          getMonthBytes() {
        java.lang.Object ref = month_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          month_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string month = 4;</code>
       * @param value The month to set.
       * @return This builder for chaining.
       */
      public Builder setMonth(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        month_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string month = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMonth() {
        
        month_ = getDefaultInstance().getMonth();
        onChanged();
        return this;
      }
      /**
       * <code>string month = 4;</code>
       * @param value The bytes for month to set.
       * @return This builder for chaining.
       */
      public Builder setMonthBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        month_ = value;
        onChanged();
        return this;
      }

      private double high_ ;
      /**
       * <code>double high = 5;</code>
       * @return The high.
       */
      public double getHigh() {
        return high_;
      }
      /**
       * <code>double high = 5;</code>
       * @param value The high to set.
       * @return This builder for chaining.
       */
      public Builder setHigh(double value) {
        
        high_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double high = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearHigh() {
        
        high_ = 0D;
        onChanged();
        return this;
      }

      private double low_ ;
      /**
       * <code>double low = 6;</code>
       * @return The low.
       */
      public double getLow() {
        return low_;
      }
      /**
       * <code>double low = 6;</code>
       * @param value The low to set.
       * @return This builder for chaining.
       */
      public Builder setLow(double value) {
        
        low_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double low = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearLow() {
        
        low_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object key_ = "";
      /**
       * <code>string key = 7;</code>
       * @return The key.
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string key = 7;</code>
       * @return The bytes for key.
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string key = 7;</code>
       * @param value The key to set.
       * @return This builder for chaining.
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string key = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearKey() {
        
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <code>string key = 7;</code>
       * @param value The bytes for key to set.
       * @return This builder for chaining.
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        key_ = value;
        onChanged();
        return this;
      }

      private int year_ ;
      /**
       * <code>int32 year = 8;</code>
       * @return The year.
       */
      public int getYear() {
        return year_;
      }
      /**
       * <code>int32 year = 8;</code>
       * @param value The year to set.
       * @return This builder for chaining.
       */
      public Builder setYear(int value) {
        
        year_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 year = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearYear() {
        
        year_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object date_ = "";
      /**
       * <code>string date = 9;</code>
       * @return The date.
       */
      public java.lang.String getDate() {
        java.lang.Object ref = date_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          date_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string date = 9;</code>
       * @return The bytes for date.
       */
      public com.google.protobuf.ByteString
          getDateBytes() {
        java.lang.Object ref = date_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          date_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string date = 9;</code>
       * @param value The date to set.
       * @return This builder for chaining.
       */
      public Builder setDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        date_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string date = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearDate() {
        
        date_ = getDefaultInstance().getDate();
        onChanged();
        return this;
      }
      /**
       * <code>string date = 9;</code>
       * @param value The bytes for date to set.
       * @return This builder for chaining.
       */
      public Builder setDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        date_ = value;
        onChanged();
        return this;
      }

      private double close_ ;
      /**
       * <code>double close = 10;</code>
       * @return The close.
       */
      public double getClose() {
        return close_;
      }
      /**
       * <code>double close = 10;</code>
       * @param value The close to set.
       * @return This builder for chaining.
       */
      public Builder setClose(double value) {
        
        close_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double close = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearClose() {
        
        close_ = 0D;
        onChanged();
        return this;
      }

      private double open_ ;
      /**
       * <code>double open = 11;</code>
       * @return The open.
       */
      public double getOpen() {
        return open_;
      }
      /**
       * <code>double open = 11;</code>
       * @param value The open to set.
       * @return This builder for chaining.
       */
      public Builder setOpen(double value) {
        
        open_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double open = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearOpen() {
        
        open_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object day_ = "";
      /**
       * <code>string day = 12;</code>
       * @return The day.
       */
      public java.lang.String getDay() {
        java.lang.Object ref = day_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          day_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string day = 12;</code>
       * @return The bytes for day.
       */
      public com.google.protobuf.ByteString
          getDayBytes() {
        java.lang.Object ref = day_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          day_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string day = 12;</code>
       * @param value The day to set.
       * @return This builder for chaining.
       */
      public Builder setDay(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        day_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string day = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearDay() {
        
        day_ = getDefaultInstance().getDay();
        onChanged();
        return this;
      }
      /**
       * <code>string day = 12;</code>
       * @param value The bytes for day to set.
       * @return This builder for chaining.
       */
      public Builder setDayBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        day_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.example.model.protobuf.StockTicks)
    }

    // @@protoc_insertion_point(class_scope:org.example.model.protobuf.StockTicks)
    private static final org.example.model.protobuf.StockTicksProto.StockTicks DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.example.model.protobuf.StockTicksProto.StockTicks();
    }

    public static org.example.model.protobuf.StockTicksProto.StockTicks getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StockTicks>
        PARSER = new com.google.protobuf.AbstractParser<StockTicks>() {
      @java.lang.Override
      public StockTicks parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StockTicks(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<StockTicks> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StockTicks> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.example.model.protobuf.StockTicksProto.StockTicks getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_model_protobuf_StockTicks_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_model_protobuf_StockTicks_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020StockTicks.proto\022\032org.example.model.pr" +
      "otobuf\"\265\001\n\nStockTicks\022\016\n\006volume\030\001 \001(\003\022\016\n" +
      "\006symbol\030\002 \001(\t\022\n\n\002ts\030\003 \001(\t\022\r\n\005month\030\004 \001(\t" +
      "\022\014\n\004high\030\005 \001(\001\022\013\n\003low\030\006 \001(\001\022\013\n\003key\030\007 \001(\t" +
      "\022\014\n\004year\030\010 \001(\005\022\014\n\004date\030\t \001(\t\022\r\n\005close\030\n " +
      "\001(\001\022\014\n\004open\030\013 \001(\001\022\013\n\003day\030\014 \001(\tB\021B\017StockT" +
      "icksProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_example_model_protobuf_StockTicks_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_example_model_protobuf_StockTicks_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_model_protobuf_StockTicks_descriptor,
        new java.lang.String[] { "Volume", "Symbol", "Ts", "Month", "High", "Low", "Key", "Year", "Date", "Close", "Open", "Day", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
